spring.application.name=MagicFridgeAI

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:magicfridge}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

ollama.api.url=${OLLAMA_URL_API}
ollama.model=${OLLAMA_MODEL:llama3.2}
